import React, { useState, useEffect } from 'react';
import { 
  X, 
  Smartphone, 
  RefreshCw, 
  MessageSquare, 
  ExternalLink, 
  Clock, 
  CheckCheck, 
  Copy,
  Check,
  SendHorizontal
} from 'lucide-react';
import api from '../api/axios';

export default function LiveSimulatorModal({ isOpen, onClose }) {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(false);
  const [mode, setMode] = useState('mock_simulator');
  const [copiedIndex, setCopiedIndex] = useState(null);

  const fetchLogs = async () => {
    setLoading(true);
    try {
      const res = await api.get('/system/sms-logs');
      if (res.data.success) {
        setLogs(res.data.data);
        setMode(res.data.mode);
      }
    } catch (err) {
      console.error('Failed to fetch SMS logs', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      fetchLogs();
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleCopy = (text, idx) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#030409]/80 backdrop-blur-xl animate-fade-in">
      <div className="relative w-full max-w-2xl bg-[#0a0d1e] border border-white/10 rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        
        {/* Glow Header */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-brand-500 via-accent-500 to-indigo-500" />

        {/* Header */}
        <div className="px-6 py-5 border-b border-white/[0.08] flex items-center justify-between bg-[#070914]/80">
          <div className="flex items-center gap-3.5">
            <div className="w-10 h-10 rounded-2xl bg-brand-500/10 border border-brand-500/20 flex items-center justify-center text-brand-400 shadow-sm">
              <Smartphone className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-display text-base font-bold text-white tracking-tight">
                  Virtual SMS Handset Simulator
                </h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-brand-500/15 text-brand-300 border border-brand-500/30">
                  Mock Telephony
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Live stream of carrier SMS dispatches generated by the backend engine
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={fetchLogs}
              disabled={loading}
              className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-white/5 transition-colors"
              title="Refresh logs"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin text-brand-400' : ''}`} />
            </button>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-white/5 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-4 flex-1">
          {logs.length === 0 ? (
            <div className="text-center py-14 px-4 border border-dashed border-white/10 rounded-3xl bg-white/[0.01]">
              <div className="w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center mx-auto mb-3 text-slate-500">
                <MessageSquare className="w-6 h-6" />
              </div>
              <h4 className="text-sm font-semibold text-slate-200 mb-1">No Dispatched SMS Transmissions Yet</h4>
              <p className="text-xs text-slate-400 max-w-sm mx-auto">
                Compose and dispatch a message from the Dashboard. The simulated SMS payload and access link will appear here instantly.
              </p>
            </div>
          ) : (
            logs.map((item, index) => (
              <div 
                key={item.sid || index}
                className="bg-[#060813]/90 border border-white/[0.08] rounded-2xl p-5 shadow-lg hover:border-brand-500/30 transition-all group relative overflow-hidden"
              >
                <div className="absolute top-0 left-0 bottom-0 w-1 bg-gradient-to-b from-brand-500 to-accent-500" />
                
                {/* Meta info */}
                <div className="flex items-center justify-between text-xs text-slate-400 mb-3 pb-2.5 border-b border-white/5">
                  <div className="flex items-center gap-2.5">
                    <span className="font-semibold text-brand-300 font-mono flex items-center gap-1">
                      <SendHorizontal className="w-3 h-3 text-brand-400" />
                      {item.to}
                    </span>
                    <span className="text-[10px] px-2 py-0.5 rounded-md bg-white/5 text-slate-400 font-mono border border-white/5">
                      SID: {item.sid}
                    </span>
                  </div>
                  <div className="flex items-center gap-1.5 text-slate-400 font-mono text-[11px]">
                    <Clock className="w-3.5 h-3.5 text-accent-400" />
                    <span>{new Date(item.sentAt).toLocaleTimeString()}</span>
                  </div>
                </div>

                {/* SMS Body Bubble */}
                <div className="bg-[#0f1429] border border-white/5 rounded-xl p-3.5 text-xs text-slate-200 leading-relaxed font-sans mb-3.5 shadow-inner">
                  <p className="whitespace-pre-wrap">{item.body}</p>
                </div>

                {/* Actions & Target Link */}
                <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
                  <button
                    onClick={() => handleCopy(item.accessUrl, index)}
                    className="flex items-center gap-1.5 text-[11px] font-medium text-slate-300 hover:text-white px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 transition-colors"
                  >
                    {copiedIndex === index ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span className="text-emerald-400 font-semibold">Copied Link</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-slate-400" />
                        <span>Copy Token URL</span>
                      </>
                    )}
                  </button>

                  <a
                    href={item.accessUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand-300 hover:text-white px-3.5 py-1.5 rounded-lg bg-brand-500/15 hover:bg-brand-500/25 border border-brand-500/30 transition-all shadow-sm"
                  >
                    <span>Inspect Recipient View</span>
                    <ExternalLink className="w-3.5 h-3.5" />
                  </a>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer Note */}
        <div className="px-6 py-3.5 bg-[#070914] border-t border-white/[0.08] text-[11px] text-slate-400 flex items-center justify-between">
          <span className="flex items-center gap-2">
            <CheckCheck className="w-4 h-4 text-emerald-400 shrink-0" />
            Active simulation sandbox: Twilio dispatch logic verified without billable SMS fees.
          </span>
          <span className="font-mono text-slate-400 font-medium">{logs.length} logged messages</span>
        </div>

      </div>
    </div>
  );
}
